### ISSUE TITLE
master is behind gitlab master branches for atmos_param and atmos_shared by a few commits

### ISSUE THREAD

**Issue by nikizadehgfdl** [NOAA-GFDL/atmos_phys#2]
I cannot use this repo in post-xanadu xmls because of some commits are missing which result answer changes for ESM4. 
Particularly, in gitlab master 

- [atmos_shared/tracer_driver/tropchem_driver.F90](https://github.com/NOAA-GFDL/atmos_phys/blob/master/atmos_shared/tracer_driver/tropchem_driver.F90#L255) has a modified namelist (file_dry has moved to atmos_tracer_utilities_nml)

- [atmos_shared/tracer_driver/atmos_tracer_utilities.F90](https://github.com/NOAA-GFDL/atmos_phys/blob/master/atmos_shared/tracer_driver/atmos_tracer_utilities.F90#L187) the list name wet_dep_nml is changed to atmos_tracer_utilities_nml

There might be more diffs that I am missing since they are not being tested by our xmls.

**Comment by thomas-robinson** [comment]
This is not a development repository or a gitlab mirror.  This repo is only meant for use with public model releases.  The internal GFDL code owners would have to approve pushing those changes out to GitHub. 

The head of this repository should match the tag xanadu_esm4_20190304.

**Comment by nikizadehgfdl** [comment]
Closing.
